[build]
  # Build command for React app
  command = "npm run build"
  
  # Directory to publish (React build output)
  publish = "build"

[build.environment]
  # Node.js version to use
  NODE_VERSION = "18"

# Redirect rules (alternative to _redirects file)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
